# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sheng/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/sheng

PRODUCT_COPY_FILES += \
    vendor/xiaomi/sheng/proprietary/system/etc/sysconfig/qti_whitelist.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/qti_whitelist.xml \
    vendor/xiaomi/sheng/proprietary/system_ext/etc/sysconfig/qti_telephony_system_packages_config.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/sysconfig/qti_telephony_system_packages_config.xml

PRODUCT_PACKAGES += \
    QtiTelephonyService
